### ISSUE TITLE
Bane card present without Young Witch in the kingdom

### ISSUE THREAD

**Issue by noscgag** [blakevanlan/KingdomCreator#128]
I selected Empires, Renaissance, and Menagerie and told it to Randomize. It chose:

Crown, Enchantress, Farmer's Market, Wild Hunt, Hostelry, Scrap, Stockpile, Hideout, Patron, and Villain, with Menagerie as the Bane card

It also selected Delve, Arena, and Market Towns for Event, Landmark, and Ally. These are fine.

Oddly, it also selected three Boons, and said I should play with Platinum/Colony and Shelters. These are odd because I didn't tell it to use Nocturne, Prosperity, or Dark Ages.
I'll add some screenshots showing all the cards.

![image](https://user-images.githubusercontent.com/11871175/197873171-15184e11-f7e7-45a7-94d4-59df1401166d.png)
![image](https://user-images.githubusercontent.com/11871175/197873348-018e3702-9b5b-44b2-aacd-ab85f5f3bc00.png)

**Comment by gillesgros** [comment]
Hello,

I think it is due to the way the query string is handle.
@markbrockettrobson , @blakevanlan :
what is your prefrence on the 2 following options 
  - applying the query string, and setting the expansion acordingly so the query is coherent with the sets selected
  - parsing the query string, based on the selected sets,  and removing the kingdoms that are not coherent with the selectec sets.
So and the end, the kingdoms randomized and the selected sets are coherent onr with another.

My prefernce is number 2: removed kingdoms based on selected sets

**Comment by gillesgros** [comment]
deployed
