### ISSUE TITLE
Possibility to have your own recommended kingdoms local file 

### ISSUE THREAD

**Issue by gillesgros** [blakevanlan/KingdomCreator#25]
It might be interesting to allow the user to display his personal recommended kingdoms that are stored in a local file. File should be formatted as current recommended kingdoms

I am trying to build that, but my knowledge in vue, yaml make it difficult.

If you want to see where I am at, take a look at: [https://71yeti.fr]( https://71yeti.fr/)

The feature that I build so far are: 

internal (not visible to users)
- put card image by set (looks cleaner in folders)
- avoid defining cost for cards that have no cost (landmarks)

- add possibility to display French card image (easier to fetch card in boxes)
- show all cards from a Dominion Set
- add promo cards that were missing (summon, sauna/avanto, church, captain, dismantle)

in rules
- remove the set label (The box image shows it)

in recommended kingdoms
- show name of recommended kingdoms 
- ability to filter by set.
- ability to navigate to recommended kingdoms set 
- Possibility to show the recommended kingdoms of all sets (for searching thru filter)

The feature I am working on is the "Personal Sets" entry in recommended kingdoms page.
So far, I am able to read the local file content but not yet to transform it as a dominionKingdoms object.
Can you give me an hint on how to parse the file as you have done it for all recommended kingdoms.
Once done, It should be easy to display as for the other sets.

Thanks for your feedback.

Gilles

**Comment by blakevanlan** [comment]
Hi, 

Answer inline below.

> The feature I am working on is the "Personal Sets" entry in recommended kingdoms page.
So far, I am able to read the local file content but not yet to transform it as a dominionKingdoms object.
Can you give me an hint on how to parse the file as you have done it for all recommended kingdoms.
Once done, It should be easy to display as for the other sets.

I'm not sure going down the .yaml path is correct. Have you considered using something else like Google Sheets as the source for saved kingdoms?

If you do still want to trying and go down the local file route, you should be able to pretty easily just serialize the list of card ids and store in JSON. Alternative, you could also just grab the URL itself since that encodes the set information as well.

> add promo cards that were missing (summon, sauna/avanto, church, captain, dismantle) in rules

If you want to open a PR just for these promo cards I'd be happy to add them. Just haven't gotten around to doing it yet (and I selfishly don't own them myself so haven't need them!)

> add possibility to display French card image 

I've thought about adding a localized version of the site for more languages but haven't gotten very far with it. Do you have images of all the French card already or just a subset?

**Comment by gillesgros** [comment]
Hello,

I have finalized the personnal kingdoms file and the abilty to filter in the list of recommended kingdoms to find a suited kingdoms more easily.

For French Translation, i went the image way.

Have a look at [https://www.71yeti.fr](https://www.71yeti.fr).

I still need to finalized some french images.
I also would like to add the ability to filter recommended kingdoms with deck including a special card or excluding it. Ia bit like what you have done when replacing a card in randomize feature.
What are your though on that.

**Comment by blakevanlan** [comment]
Hi,

I'd love to use the French images instead of just the translations of the French cards. I didn't have images for the German or Dutch cards so translations was the best I can do. Let me know when the dump of cards is ready and I'd love to add it to the site. 

I'm not sure on the recommended kingdoms additions. Here are my thoughts:
* **Jump to top**: Very is handy! - visually it's pretty prominent so I think it'd tone down the back and shrink the icon size (may 24x24?)
* **Jump to recommended kingdom**: Neat but not always useful - could it be hidden in a dropdown of some kind that could be expanded?
* **Filter by Set**: I'm not sure on the usefulness of this feature. I always imagine this page as a way to explore recommended kingdoms and I'm not sure it requires this level of filtering. The filtering requires a lot of tapping to get down to a subset of say 5-10 sets and at that point you might as well of scrolled down the list

I love that you've taken the time to do all this work on your own!  😁By all means keep what you have on the site if that's what you'd prefer but I'm also happy to spend some time integrating the features back into this repo.

**Comment by gillesgros** [comment]
Hello,

time has gone by, but I am still using the version I Build.
I a not confortable with pull request sorry. And I have modified quite extensively cards organisation (by set).
at   https://www.71yeti.fr is still my last version updated with your last change.
Tell me if you want a full package to integrate some or all the pieces.

**Comment by gillesgros** [comment]
deployed
